### ISSUE TITLE
specifying multiple interface is not working

### ISSUE THREAD

**Issue by lsimard** [ntop/PF_RING#127]
Using pfcount, when I try to capture from multiple interface at the same time, only the first one seems to be used.

```
# pfcount -i p2p3,p2p1
Using PF_RING v.6.5.0
I/O Control error [p2p3,p2p1]
```

**Comment by cardigliano** [comment]
@lsimard I am not able to reproduce this on my machine, 
as you can see it is able to capture traffic from interface 4 regardless of the order:

# cat /proc/net/pf_ring/dev/eno1/info | grep Index

Index:             4

# cat /proc/net/pf_ring/dev/eno2/info | grep Index

Index:             2

# ./pfcount -i eno1,eno2 -v 1 -m -N 1 | grep if_index

15:52:28.419760268 [TX][_if_index=4_][00:25:90:D4:CC:F9 -> 00:25:90:47:2D:1A] [IPv4][192.168.2.222:22 -> 192.168.2.221:52236] [l3_proto=TCP][hash=2169557475][tos=16][tcp_seq_num=2186243075] 

# ./pfcount -i eno2,eno1 -v 1 -m -N 1 | grep if_index

15:52:35.315047953 [TX][_if_index=4_][00:25:90:D4:CC:F9 -> 00:25:90:47:2D:1A] [IPv4][192.168.2.222:22 -> 192.168.2.221:52236] [l3_proto=TCP][hash=2169557475][tos=16][tcp_seq_num=2186246003]

**Comment by capitainealbator** [comment]
Hi Alfredo,

Sorry for the delayed response; it's been vacation season. :) I work with Luke and we were able to determine the issue was introduced with this commit:
https://github.com/ntop/PF_RING/commit/304ef10beca528750da3e2e048071efb846758ea

Ever since then we haven't been able to capture traffic from multiple interfaces. The function dev_change_flags is returning 0 but it looks like the interfaces aren't really set to promiscuous mode? However, if we make the interfaces promiscuous via the operating system first, then everything works fine when we launch pf_ring.

Right now we're on a physical machine with CentOS 6.6 and kernel 2.6.32-642.3.1.el6.x86_64. Our ethernet card model is Broadcom Corporation NetXtreme BCM5720 Gigabit Ethernet PCIe.

We have a workaround for the moment but do you have any idea what could cause this?

Thanks

**Comment by cardigliano** [comment]
@capitainealbator I just realised I didn't reply to your last comment, please note this has been fixed.
