### ISSUE TITLE
How to set filters in PF_RING ZC?

### ISSUE THREAD

**Issue by rezaeimh7** [ntop/PF_RING#132]
I am using Pcap for packet capturing and trying to migrate to PF_RING ZC.  Need to capture packets from specific IP which are coming to specific port number. i use the following filters in pcap: 
`port 514 and (host 10.0.77.68 or host 10.0.76.68)`
 how can i implement such a filter in PF_RING ZC?

MY NIC= Intel 82599.

**Comment by rezaeimh7** [comment]
can anybody help me?
@lucaderi , @crdigliano .

**Comment by cardigliano** [comment]
Hi @mr-mohsen 
sorry for late reply, you have 2 options here: bpf or hw filtering rules.
1. BPF:

If you are using the standard PF_RING API you can set a BPF filter with:
int pfring_set_bpf_filter(pfring *ring, char *filter_buffer)
It will use a userspace engine when capturing with ZC, otherwise it will use a kernel-space engine.

If you are using the PF_RING ZC API, you should handle userspace filtering in your application, it's fairly simple, look for "userspace_bpf" in userland/lib/pfring.c as example.
1. Hw filtering rules

You can use this if all your rules have the same mask (e.g. dst ip and dst port)
If you are using the standard PF_RING API you should use:
int pfring_add_hw_rule(pfring *ring, hw_filtering_rule *rule) 

If you are using the PF_RING ZC API you should use:
int pfring_zc_add_hw_rule(pfring_zc_queue *queue, hw_filtering_rule *rule);

Please look at pfcount_82599.c for examples for populating the hw_filtering_rule struct.

Alfredo
