### ISSUE TITLE
General question about ZC APIs

### ISSUE THREAD

**Issue by szarea** [ntop/PF_RING#203]
Hi,
I would greatly appreciate if you could respond to the following questions:

pfring_zc_create_cluster
========================
1. What is "metadata_len" in pfring_zc_create_cluster?
2. Should I assume that I need to create a cluster for each cpu package/node?
3. Should I assume that p"fring_zc_create_cluster" has only one worker thread?
4. PREFETCH_BUFFERS macro is set to 8 in your examples. Is 8 the most optimized value or does it depend on the available resources in the system?
5. QUEUE_len macro is set to 8192 in your examples. Is 8192 the most optimized value or does it depend on the available resources in the system?
6. MAX_CARD_SLOTS macro is set to 32768 in your examples. Is 32768 the most optimized value or does it depend on the available resources in the system?

pfring_zc_open_device
=====================
7. What is "Optional flags" for? what are the possible values?

pfring_zc_create_buffer_pool
=============================
8. What is the optimal value for "pool_len", assuming the system has huge memory resources?

IP fragmentation 
===========================
Do you have any stats/metrics on performance impact of ip fragmentation?
Thank you,
Steven

**Comment by cardigliano** [comment]
1. metadata_len can be used to extend the size of the pfring_zc_pkt_buff for adding custom metadata for the application, you can access that memory in pfring_zc_pkt_buff.user[]
2. it is not mandatory, however it is recommended in order to optimise memory accesses (it meanly depends on the application design)
3. pfring_zc_create_cluster just preallocates some (memory) resources, you can use as many worker threads as you need
4. 8 is the number of buffers used by the workers in burst mode (see the doxygen documentation)
5. queue_len depends on the available memory, 8192 is "usually enough"
6. 32768 is the maximum rx/tx ring size on Intel cards
7. all optional flags are described in pfring_zc.h (or the doxygen documentation)
8. pool_len depends on the number of buffers you want to assign to each thread or processes for traffic processing (you can reserve buffers in pools and assign pools to threads and processes, to keep aside packets for instance)
As of fragmentation, from the api point of view, working with raw packets, a fragment is like any other packet, thus there is no impact.
