### ISSUE TITLE
Monitoring traffic in zc mode

### ISSUE THREAD

**Issue by Skryabind** [ntop/PF_RING#22]
When I use igb driver with 1G card and work with interface in zc mode, I still can to show a traffic stats by ifstat or snmp.
But when I use 10G card and use ixgbe driver, ifstat shows nothing. How to show traffic counters in such issue? In both cases I load a drivers by load_driver.sh.

**Comment by cardigliano** [comment]
The problem is that ifstat is reading stats from the linux device, which is unaware of packets received by ZC sockets (kernel is bypassed). I applied a patch now to update the linux device with stats from card registers. Please check and let me know, probably stats updates are not really smooth, but you should get reliable absolute stats.

**Comment by Skryabind** [comment]
Now ifstat show only incoming traffic, outgoing counters is stil zero.

**Comment by cardigliano** [comment]
Fixed, please check latest code.

**Comment by Skryabind** [comment]
Yes, It works, Thank you!
