### ISSUE TITLE
Driver for e1000

### ISSUE THREAD

**Issue by tianchao-haohan** [ntop/PF_RING#260]
It seems that e1000e could not be used in e1000. So, could you please support e1000 too?
e1000 was widely used in vmware virtual platform, for example, esxi.

**Comment by cardigliano** [comment]
@tianchao-haohan e1000e and e1000 are two different drivers and chipset families, e1000 supports old PCI-X adapters, that's why it's not supported. However we will consider adding e1000 to support virtual adapters. Please note this would not provide native performance anyway as e1000 adapters are emulated by the hypervisor, thus the backend overhead would be still in place.
