### ISSUE TITLE
Get Capture Device Name With Each Packet

### ISSUE THREAD

**Issue by Vehere-VIPL** [ntop/PF_RING#300]
Hello,

How can I get Capture Device Name (like eth0 or p6p1 etc) per packet with PF_RING+ZC?

**Comment by Vehere-VIPL** [comment]
Using PF_RING 6.6.0.

**Comment by Vehere-VIPL** [comment]
Yes multiple interfaces are used.

pfring_zc_create_cluster [To Create Cluster]
pfring_zc_get_packet_handle
pfring_zc_open_device
pfring_zc_create_queue
pfring_zc_run_balancer

pfring_zc_recv_pkt [To Receive Packets]
pfring_zc_pkt_buff_data[To Get Frame]

**Comment by cardigliano** [comment]
You should set an interface id in the packet handle when you receive the packet from an interface with pfring_zc_recv() or in a balancer distribution_func. In order to do this, you can use the hash field in the pfring_zc_pkt_buff if you don't need it,  or you can add more metadata in the user[] field (please note you should set the correct metadata length when calling pfring_zc_create_cluster() in this case).

typedef struct {
  u_int16_t len;         /**< Packet length. */
  u_int16_t flags;       /**< Packet flags. */
  u_int32_t hash;        /**< Packet hash. */
  pfring_zc_timespec ts; /**< Packet timestamp (nsec) */
  u_char user[];         /**< Start of user metadata, if any. */
} pfring_zc_pkt_buff;
