### ISSUE TITLE
zbalance_ipc and Bro

### ISSUE THREAD

**Issue by curtisxk38** [ntop/PF_RING#357]
Hello,
Is this [link](https://www.ntop.org/pf_ring/best-practices-for-using-bro_ids-with-pf_ring-zc-reliably/) still accurate for the best way to use PF_RING:ZC and Bro?
My issue is that my Bro workers are crashing using PF_RING:ZC (and they worked fine using AF_PACKET as a load balancer)
I am running zbalance_ipc as `zbalance_ipc -i zc:em2 -l /var/log/zbalance.log -c 97 -n 6 -m 1 -a -r 0:dummy0 -r 1:dummy1 -r 2:dummy2 -r 3:dummy3 -r 4:dummy4 -r 5:dummy5 `

I also have some questions about the flags for zbalance_ipc.
1. Does the IP hash `-m 1` only use the source and destination IPs (not the ports or protocol)?
2. I read in previous issue that `-a` is: 
"active wait mode the CPU is spinning checking for new packets, otherwise, in passive mode, it waits using poll/usleep before checking for new packets."
Is there a situation in which it is better to disable or enable active wait? How should I know whether to use this flag or not?
3. Previously I was using `-g` to pin zbalance_ipc to a core, but I noticed that using `ps -o pid,psr,comm <zbalance pid>` would report that zbalance_ipc was running on a core that wasn't the paramter to the `-g` flag. Is this a known issue? I just used `taskset` instead to pin it which worked.

Thanks for your time

**Comment by cardigliano** [comment]
@curtisxk38 are you saying that Bro is crashing due to ZC? Actually he is capturing from dummy interfaces, thus there should be no direct relation. Do you see malformed packets?
1. -m 1 is based on IP only yes, -m 4 uses port also
2. -a should be used when you experience packet loss at high rates (above 10 Mpps), please note it uses more CPU, thus better to disable it if it's not needed
3. -g seems to be working for me, please note that it sets the affinity for the worker thread, while the main thread is floating (as it does not actually use much cpu). Please check cpu utilisation in top or htop (you can see all threads there)

**Comment by curtisxk38** [comment]
Thank you for answering my questions. I was just wondering if there was a newer/better way to use zbalance with Bro. But I agree it must be a Bro problem since it is capturing from the dummy interface. I will ask on their mailing list.

**Comment by radoslawc** [comment]
@curtisxk38 what's your node configuration and are you using bro pf_ring plugin (from aux/plugins) or did you build bro against pf_ring's libpcap?

**Comment by curtisxk38** [comment]
@radoslawc @cardigliano 
I found out that the kernels OOM killer terminated the Bro worker, it had nothing to do with PF_RING:ZC or zbalance_ipc. 
Thanks for your help
