### ISSUE TITLE
Support for DNA

### ISSUE THREAD

**Issue by sajishv** [ntop/PF_RING#406]
Hi, 

I would like to run PF_RING on VMs with VMWare.
As ZC is not supported with VMWare ( could not find any references ) and is only supported with KVM, we are looking to implement our solution using DNA (https://www.ntop.org/pf_ring/10-gbit-pf_ring-dna-on-virtual-machines-vmware-and-kvm/).

Can you please let me know if the current drivers support DNA? otherwise, where can i find code to use DNA? 

Thanks,
Nair

**Comment by cardigliano** [comment]
Hi @sajishv, both ZC and DNA (deprecated) can be used with DirectIO (PCI Passthrough) on VMWare.

**Comment by sajishv** [comment]
Hi @cardigliano, 

We are more interested in ZC. 
Can you please let me know if there is a document like https://www.ntop.org/guides/pf_ring/vm/kvm_zc.html for VMWare (PCI Passthrough).

If we have to go with DNA can you please let me know where can i find the code/drivers for the same? 

Thanks,
Nair.

**Comment by cardigliano** [comment]
Hi Nair
as I said there is no need to go with DNA (and it is actually not supported) as ZC is a superset of it,
in order to configure the passthrough (DirectPath I/O) on the hypervisor please refer to the VMWare documentation (e.g. https://kb.vmware.com/s/article/1010789). Once the passthrough is configured, you can follow the standard instructions for configuring the drivers on the guest VM http://www.ntop.org/guides/pf_ring/get_started/packages_installation.html
