### ISSUE TITLE
[ZC] Multi-balancer documentation

### ISSUE THREAD

**Issue by mryamac** [ntop/PF_RING#440]
Hello,
I have a complex distribution function and more than 4 interfaces. What I need to do is that I will try to run multiple balancers to send packets to the same packet consumer threads. Here is the question about balancer. Assume that I will use two balancers. Each balancer has different interfaces but the output queue is the same.
Do I need to create two clusters or one is enough? (I will test it if I use two, there are some missing packets)
I thought balancer and consumer threads use the same queue, it means that queue has thread-safe operations. Therefore two balancers can use the same output queue. Am I right?
I couldn't find any documentation, so I just do it intuitively. If you inform us about clusters and queue, I will be very happy. Thanks all.

**Comment by cardigliano** [comment]
> Each balancer has different interfaces but the output queue is the same.

You cannot use the same queue in different balancers as queues are single-producer (that would lead to corruptions) 

> Do I need to create two clusters or one is enough? (I will test it if I use two, there are some missing packets)

If this is a multithreaded application, I recommend to create a single cluster in order to run everything in the same domain, otherwise you should pay attention mixing buffers from different clusters.

> I thought balancer and consumer threads use the same queue, it means that queue has thread-safe operations. Therefore two balancers can use the same output queue. Am I right?

Queues are SPSC (single-producer single-consumer), this means that you can have both the balancer and the consumer, but you cannot have multiple producers or multiple consumers without locking.

**Comment by mryamac** [comment]
As I understand, It is not possible to run multi-balancer with single output queue using the built-in library.
I will try to write own balancer. Thank you again

**Comment by cardigliano** [comment]
In order to do that in a lockless way, you need one output queue per balancer, and aggregate from all queues on the consumer side.. and you can do this using the balancer provided by ZC. If you want multiple balancers sending to the same queue, you need locking, but we want to avoid this in ZC for performance reasons.
