### ISSUE TITLE
How to cross compile PF_RING

### ISSUE THREAD

**Issue by Anticom** [ntop/PF_RING#60]
Since the project doesn't seem to be based on automake, how do i cross compile it?
I was able to locate the following `configure` scripts:
- ./kernel/configure
- ./drivers/ZC/intel/configure
- ./drivers/DNA/configure
- ./userland/tcpdump-4.1.1/configure
- ./userland/lib/configure
- ./userland/libpcap-1.6.2-ring/configure
- ./package/ubuntu/configure
- ./package/rpm/configure

However only the following _(- assuming the 3rd party ones -)_ ones actually had a `--host` option:
- ./userland/tcpdump-4.1.1/configure
- ./userland/libpcap-1.6.2-ring/configure

Since utilizing the `--host` option is the only way known to me to conveniently cross-compile a project i'm kind of stuck with how to cross-compile PF_RING properly.

**Comment by amulpatel** [comment]
Hello,

I am also trying to cross compile PF_RING for MIPS.

I had compiled kernel module successfully for MIPS but issue in compiling libraries.

I see PF_RING-6.6.0-stable/userland/lib/libs contain some archived for x86_64 (e.g. libpfring_fiberblaze_x86_64.a) which is extracted during compilation.
Here all libs available in x86_64 format but I need for MIPS arch.

Does PF_RING libraries (archived libpfring_fiberblaze_x86_64.a ) are available for MIPS or source code available so that I can compile and create all .o files (e,g pfring_zc_dev_e1000.o ) for MIPS ?

Following are the Error while linking for MIPS arch since pfring_zc_dev_e1000.o is in x86 format.

pfring_zc_dev_e1000.o: could not read symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[4]: *** [libpfring.so] Error 1

[root@PC lib]$ file pfring_zc_dev_e1000.o
pfring_zc_dev_e1000.o: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped
[root@PC lib]$

Thanks,
Amul Patel

**Comment by cardigliano** [comment]
@amulpatel as you noticed all binary licenses are provided for Intel x86_64 only, we do not provide them for MIPS. However the configure script should detect that you are running on non-x86_64 and disable the compilation of those libraries. I made some change to the configure to make sure this is the case, please update from git and let us know.

**Comment by amulpatel** [comment]
Thanks,
I am compiling pf_ring with openwrt and modified most of the stuff to make it compatible with openwrt MIPS package.
I successfully compiled kernel module & libs with disabling ZERO_COPY but if we disable zc then pf_ring (including snort daq) will be used as standard (not zc) and will not use ZERO_COPY right?
What if we want to use PF_RING with Zero Copy which is the my intention to use pf_ring?

Thanks,
Amul Patel

**Comment by cardigliano** [comment]
@amulpatel please note PF_RING ZC supports Intel only

**Comment by amulpatel** [comment]
Thank you very much cardigliano for confirmation.
I will build accordingly.

**Comment by amulpatel** [comment]
Hi Alfredo,

Thanks for help,

Consider I need to support PF_RING with Zero copy for MIPS then is there any way to achieve it?
Can I get source code of archived libs and I compile my self for MIPS arch or you can provide support for MIPS?

my email-id amulpatel.biz@gmail.com for offline discussion.

Thanks in Advance.
Amul Patel

**Comment by cardigliano** [comment]
@amulpatel PF_RING Zero-Copy is not supported on MIPS as we privide binaries for Intel only as I said, you should use standard PF_RING.
