### ISSUE TITLE
PF_RING's libpcap segfault when used by Zeek loadbalanced on multiple cores

### ISSUE THREAD

**Issue by g4laad** [ntop/PF_RING#666]
Hi,

I am tying to use Zeek with PF_RING on an Accolade NIC, the 40 Ku. However, whenever I use more than 1 worker, many of them crashes with the following error:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fdf8efb2a20 in __pfring_anic_ready.isra.17 () from /opt/PF_RING/lib/libpcap.so.1
```

I used the following guide for Zeek's compilation with PF_RING: https://holdmybeersecurity.com/2019/04/03/part-1-install-setup-zeek-pf_ring-on-ubuntu-18-04-on-proxmox-5-3-openvswitch/
And this guide https://www.ntop.org/guides/pf_ring/modules/accolade.html for some parameters.

My current setup is the following:
- Ubuntu 20.04
- Accolade 40Ku (4 ports of 10G) and its driver, port 1 connected
- PF_RING v.7.7.0.201012 (I used zcount --help to have this information) compiled, I have a license for PF_RING ZC so tcpdump doesn't trigger any license error (I didn't install any PF_RING ZC driver from the driver folder of PF_RING)
- Zeek  3.3.0-dev.451 (git version compiled with the libpcap from PF_RING)

**Comment by cardigliano** [comment]
@g4laad please note that Accolade requires a special configuration to use multiple rings (required by multiple workers), otherwise you will have multiple workers concurrently opening the same interface. Please take a look at anic_mfl_config in https://www.ntop.org/guides/pf_ring/modules/accolade.html

**Comment by g4laad** [comment]
I have used the following configurations:
```
 /opt/accolade/bin/anic_mfl_config -i 0 --mode=32 --blocks=64
```
Adapter 0 should loadbalance all its interfaces on 32 rings
and 
```
/opt/accolade/bin/anic_mfl_config -i 0 --mode=x8
```
Each port of adapter 0 is loadbalanced on 8 rings.

Only port 1 of the adapter 0 is UP.
I used a maximum of 8 workers (lb_procs=8) and the workers listen on anic:0:1 (pfcount and PF_RING's tcpdump can see the packets on this interface)

However, I still have some crashed workers because of the libpcap.

**Comment by cardigliano** [comment]
Hi @g4laad I think the problem is with the interface name "anic:0:1", please try specifying anic:0, Bro should add the ring automatically (anic:0@0, anic:0@1, and so on) as the port should be specified in anic_mfl_config. 
When you say this is "because of the libpcap" what do you mean exactly? Do you have a trace?

**Comment by g4laad** [comment]
Hi ! I think the issue can be closed. My error was in my config file.
In order to use an accolade NIC, each worker should listen on a different ring "anic:0@0" for ring 0 for example.

Thank you for your help.
