### ISSUE TITLE
Problem receiving big UDP packet

### ISSUE THREAD

**Issue by zinosat** [ntop/PF_RING#880]
We're running a PF_RING based application to capture UDP packets with "enable_ip_defrag=1" and noticed some packets are not received: we narrowed it down to the size of those missing packets.
mtu size is 1500 and we also tried to disable GRO/TSO via ethtool without any success.

We use linux 4.14.79 with vanilla pf_ring 7.6.0 and reproduced the same problem on current "dev" branch (a5313280c1f3eacdcf3bd7643b0feca073d4b4bc).

In particular our application can receive at maximum packets of 65493 bytes and everything bigger than that is lost.
I'm attaching a pcap file which reproduces the problem, where the packet is 65502 bytes.

thank you in advance,
Davide

[bigudp.pcap.gz](https://github.com/ntop/PF_RING/files/12259703/bigudp.pcap.gz)

**Comment by cardigliano** [comment]
@zinosat let us review the code to check if this is a defragmentation limit or depends on the max capture length currently supported by pf_ring (packets bigger than 65K are definitely not expected). I suggest to disable defragmentation in the meanwhile to avoid missing packets.

**Comment by rmbq** [comment]
Hi! Seems like i hit the same issue with current dev branch. 
I also tried with packets attached by @zinosat .
I just want to say tcpdump and wireshark successfully capture these big UDP packets. Based on [this](https://en.wikipedia.org/wiki/User_Datagram_Protocol#:~:text=The%20field%20size%20sets%20a,20%2Dbyte%20IP%20header).), max UDP size is 65,507B, so 65502 is still in a valid range, just very close to the limit.

**Comment by rmbq** [comment]
Hi @cardigliano. I investigated the issue a little bit, using @zinosat's packets.
I found a issue in `parse_pkt()` in [kernel/pf_ring.c](https://github.com/ntop/PF_RING/blob/1af5831ae0d83511f38a667c06339c6553165d6b/kernel/pf_ring.c#L2591):
`int data_len = min((u_int16_t)(skb->len + skb_displ), (u_int16_t)sizeof(buffer));`
In this case `skb->len = 65530` and `skb_displ = 14` so `skb->len + skb_displ` exceed MAX(u_int16_t).
I tried to change the line in 
`int data_len = min((u_int32_t)(skb->len + skb_displ), (u_int32_t)sizeof(buffer));`
now the packet is received but it seems to be corrupted.

Hope this helps

**Comment by cardigliano** [comment]
Weird we have a u_int16_t there.. I need to investigate to figure out why

**Comment by cardigliano** [comment]
I cleaned up the types a bit in 1930fc069e6652b6ec6b82f67d778c86f8469b13

**Comment by rmbq** [comment]
It's better but there are still issues.
i made an example [here](https://gist.github.com/rmbq/e75a53f345746af1dde6f3a448d5134f)
There is a python script to send a payload (of size -s) to IP:Port of all 0xFF
There's a C program for receive a payload with PF_RING and calculate its md5 and verify which bytes are wrong.

I use the C program like this:
` ./pfring_rcv -i enp0s8 -I 19.2.0.91 -P 15000`
and the python like this:
`python .\sendf.py -s 65507`

The last correct size is 65493, i think because 65493 + 14 (L2 hdr) + 20 (IP hdr) + 8 (UDP hdr) = 65535
From 65494 to 65507 there's some corruption, `pfring_rcv` prints:
```
Byte 65535[65493] is 136
Byte 65536[65494] is 136
Byte 65537[65495] is 0
Byte 65538[65496] is 0
Byte 65539[65497] is 0
Byte 65540[65498] is 0
Byte 65541[65499] is 0
Byte 65542[65500] is 0
Byte 65543[65501] is 0
Byte 65544[65502] is 0
Byte 65545[65503] is 0
Byte 65546[65504] is 0
Byte 65547[65505] is 0
Byte 65548[65506] is 0
```

The corrupted byte on a payload of 65507 (max supported payload) are exactly 14. Which is L2 hdr len. I was wondering if there's some miscalculation here, max IP size is 65535 without L2 hdr!

**Comment by rmbq** [comment]
Tracking down the issue, i saw in [copy_data_to_ring](https://github.com/ntop/PF_RING/blob/1930fc069e6652b6ec6b82f67d778c86f8469b13/kernel/pf_ring.c#L3024C6-L3024C6)
this line
`hdr->caplen = min_val(hdr->caplen, pfr->bucket_len - offset);`
`hdr->caplen` is 65549, `pfr->bucket_len` is 65535 and `offset `is 0.
This set `hdr->caplen` to 65535.
Increasing [MAX_CAPLEN](https://github.com/ntop/PF_RING/blob/1930fc069e6652b6ec6b82f67d778c86f8469b13/userland/lib/pfring.h#L67) to `(65535 + 14)` and calling `pfring_open` with size of 65549  instead of 65535 set `pfr->bucket_len` correctly to 65549 and the packet is received successfully.

**Comment by cardigliano** [comment]
@rmbq I increased that to 65600 to make room for additional l2 headers and round it up to 64 bytes. It should be fine now. Thank you for investigating.

**Comment by zinosat** [comment]
> @rmbq I increased that to 65600 to make room for additional l2 headers and round it up to 64 bytes. It should be fine now. Thank you for investigating.

Excellent!
Is there any chance to get a backport to 7.6.0 once we finish testing the fix? 
Thank you so much!

**Comment by cardigliano** [comment]
7.6.0 is too old and no longer updated sorry

**Comment by rmbq** [comment]
@cardigliano tested, for me it's ok
